### PR TITLE
added options

### PR DESCRIPTION
**Pull request by mchauhan3**

### CODE REVIEW

**Comment by anilshanbhag** [comment]
Getting price data from Yahoo Finance is not a good idea. The price data there is quite stale, there should be a Robinhood api endpoint for it, yet to figure it out myself.

**Comment by mchauhan3** [comment]
There is a Robinhood endpoint for it - /marketdata/options. 
However, querying it return error 403: forbidden. 
It might work if we can authenticate through https://api.robinhood.com/oauth2/token/ and use Bearer Authorization.

**Comment by mchauhan3** [comment]
Ok I have changed the price data to Robinhood, had to change authentication for marketdata to work.

**Comment by anilshanbhag** [comment]
Finally merged it, made some minor changes to function names etc.

**Pull request merged**
